# Generated by Django 4.2 on 2023-04-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('x1', models.IntegerField(blank=True, default=0, null=True)),
                ('x2', models.IntegerField(blank=True, default=0, null=True)),
                ('x3', models.IntegerField(blank=True, default=0, null=True)),
                ('y1', models.IntegerField(blank=True, default=0, null=True)),
                ('y2', models.IntegerField(blank=True, default=0, null=True)),
                ('y3', models.IntegerField(blank=True, default=0, null=True)),
                ('z1', models.IntegerField(blank=True, default=0, null=True)),
                ('z2', models.IntegerField(blank=True, default=0, null=True)),
                ('z3', models.IntegerField(blank=True, default=0, null=True)),
                ('r1', models.IntegerField(blank=True, default=0, null=True)),
                ('r2', models.IntegerField(blank=True, default=0, null=True)),
                ('r3', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
